// <auto-generated />
namespace PPC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AJUSTE_RELACIONAMENTO_TURNO_E_VAGAS2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AJUSTE_RELACIONAMENTO_TURNO_E_VAGAS2));
        
        string IMigrationMetadata.Id
        {
            get { return "201906251934129_AJUSTE_RELACIONAMENTO_TURNO_E_VAGAS2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
